version: 2
jobs:
    build:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout  # Récupère le code source dans le répertoire de travail
            - run:
                  name: Run Tests
                  command: mvn test
orbs:
    codecov: codecov/codecov@4.0.1
workflows:
    version: 2
    build:
        jobs:
            - build:
                  filters:
                      branches:
                          only:
                              - master
            - upload-to-codecov:
                jobs:
                    - checkout
                    - codecov/upload

