version: 2
jobs:
        build:
            docker:
                - image: circleci/openjdk:8-jdk
            Steps:
                - run:
                    name: Run Tests
                    command: mvn test
workflows:
    version: 2
    build:
        jobs:
            - build :
                filters:
                    branches:
                        only:
                            - master