version: 2
orbs:
    codecov: codecov/codecov@4.0.1
jobs:
    build:
        docker:
            - image: circleci/openjdk:8-jdk
        steps:
            - checkout  # Récupère le code source dans le répertoire de travail
            - run:
                  name: Run Tests
                  command: mvn test
            - run:
                  name : upload-to-codecov
                  command: bash <(curl -s https://codecov.io/bash)
            - run:
                name : generate-java-doc
                command: javadoc src/main/java/fr/univavignon/pokedex/api/* -d docs
    docs-deploy:
      docker:
        - image: node:8.10.0
      steps:
        - checkout
        - attach_workspace:
            at: docs/
        - run:
            name: Install and configure dependencies
            command: |
              npm install -g --silent gh-pages@2.0.1
              git config user.email "lyes.douki@alumni.univ-avignon.fr"
              git config user.name "lyesdki"
        - add_ssh_keys:
            fingerprints:
              - "J81m19bUhDF5nGtUpe0ZdZYGa6/0yu6iUx01eylaG3c"
        - run:
            name: Deploy docs to gh-pages branch
            command: gh-pages --dist docs/
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - docs-deploy:
          requires:
            - build

